version: "3.8"

services:
  database:
    container_name: ats-db
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ats
    ports:
      - 5430:5432
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  db:
  redis:
